# Generated by Django 3.2.15 on 2022-09-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metamaskaccount',
            name='name',
        ),
    ]
