# Generated by Django 3.2.15 on 2022-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_remove_metamaskaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metamaskaccount',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
