# Generated by Django 3.2.15 on 2022-09-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_metamaskaccount_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamaskaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
