# Generated by Django 3.2.15 on 2022-09-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_alter_metamaskaccount_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metamaskaccount',
            name='active',
        ),
        migrations.RemoveField(
            model_name='metamaskaccount',
            name='balance',
        ),
    ]
