# Generated by Django 3.2.15 on 2022-09-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0006_auto_20220920_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('result_hash', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('hash_ipfs', models.CharField(blank=True, max_length=250, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocol.metamaskaccount')),
            ],
        ),
    ]
