# Generated by Django 3.2.15 on 2022-10-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0009_alter_ipfs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipfs',
            name='account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
