# Generated by Django 3.2.15 on 2022-10-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0010_alter_ipfs_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
