# Generated by Django 3.2.15 on 2022-10-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0011_alter_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='text',
        ),
    ]
