# Generated by Django 3.2.9 on 2023-08-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0012_remove_transaction_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexinfo',
            old_name='facebook',
            new_name='discord',
        ),
        migrations.RenameField(
            model_name='indexinfo',
            old_name='instagram',
            new_name='telegram',
        ),
    ]
