# Generated by Django 3.2.9 on 2023-08-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0013_auto_20230813_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexinfo',
            old_name='discord',
            new_name='twitter',
        ),
    ]
